name: chat_mentor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  dio: ^5.0.1
  chat_bubbles: ^1.4.1
  get_storage: ^2.1.1
  url_launcher: ^6.1.10
  package_info_plus: ^3.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  flutter_launcher_icons_maker: ^0.10.2
flutter_icons: {android: launcher_icon, image_path: assets/icon/Icon.png, ios: true,
                flutter_lints: ^1.0.4 }
flutter: 
  uses-material-design: true

